---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: alpine
  name: nginx-alpine
  namespace:
    "{ .Values.namespace.name }": null
spec:
  ports:
    - port:
        "{ .Values.service.port }": null
      protocol: TCP
      targetPort:
        "{ .Values.service.port }": null
  selector:
    app: nginx
    tag: alpine
  type:
    "{ .Values.service.type }": null
