name: TechTrends - Package with Docker

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2

      - name: login to docker hub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./project/Dockerfile
          platforms: linux/amd64
          push: true
          tags: akashbalani/techtrends:latest